### ISSUE TITLE
Enable graphing functionality

### ISSUE THREAD

**Issue by hongooi73** [Azure/AzureKusto#1]
New issue since GH doesn't allow transferring across orgs

**Comment by hongooi73** [comment]
Looks like the REST API doesn't actually return a rendered image, instead relying on the client to do it using the data from the query. In which case, rather than reinventing the wheel, we should just recommend something like ggplot etc.

**Comment by hongooi73** [comment]
@alexkyllo your thoughts?

**Comment by alexkyllo** [comment]
Yeah I believe graphing is a client-side feature. The commands like `| render timechart` are commands to the user agent to plot the data a certain way.

While we could implement some `render` convenience function that calls `plot` or `ggplot` with some fixed parameters, I don't really see a need for it, since basically anyone plotting data in R is going to already have a preference for how they want to plot. I don't think I would use such a feature, personally. I would just close this as out of scope for what the package is intended to do.
