### ISSUE TITLE
weak queryconsistency option can cause query failure

### ISSUE THREAD

**Issue by alexkyllo** [Azure/AzureKusto#8]
I received an error: `Kusto.Cloud.Platform.Storage.PersistentStorage.PersistentStoragePathDoesNotExistException` when querying a Kusto cluster with the default options "queryconsistency": "weakconsistency".

We should remove this from the default options, as weakconsistency can result in query failures under certain cluster configurations.

Also, it appears that passing query options as arguments to `run_query` is not correctly overriding the default options.

**Comment by hongooi73** [comment]
> Also, it appears that passing query options as arguments to run_query is not correctly overriding the default options.

This is because extra arguments to `run_query` are treated as parameters for parameterised queries, not options. You can set query options in the endpoint:

```r
endp <- kusto_database_endpoint(server="server_url", database="dbname",
    queryconsistency="strongconsistency")
```

Although, the ability to set query options in `run_query` seems like a good thing to have. Maybe something like this?

```r
run_query(endp, "qry", .options=list(queryconsistency="strongconsistency"))
```

Here we have an extra argument `.options` that would go after `...`.

**Comment by alexkyllo** [comment]
Thanks so much, I had just forgotten that query options get passed to `kusto_database_endpoint()` rather than `run_query()`. I think this interface is fine as-is, I don't see a strong need to set different options per query on the same database. I will just look to make sure this is well documented so I don't confuse myself again!
